name: HGames
version: 0.0.1
author: Namu
main: fr.namu.hg.MainHG
commands:
  hg:
    description: Permet d'obtenir des informations concernant le plugin SD
    usage: /sd <command>
  hgames:
    description: Permet de configurer la partie de Sky Defender
    usage: /skydefender <command>
  host:
    description: Commandes des administrateurs
    usage: /host <command>
  h:
    description: Commandes des administrateurs
    usage: /h <command>